name: check

permissions:
  contents: read

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_mysql:
    runs-on: ubuntu-24.04
    services:
      database:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 123456
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          enable-cache: true
      - name: Run CI
        run: make ci

  ci_mariadb:
    runs-on: ubuntu-24.04
    services:
      database:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 123456
        options: --health-cmd="mariadb-admin ping -uroot -p${MYSQL_ROOT_PASSWORD}" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          enable-cache: true
      - name: Run CI
        run: make ci
