name: publish

permissions:
  contents: read

on:
  release:
    types:
      - created

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: release
    strategy:
      matrix:
        os: [macos-15-intel, macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          activate-environment: true
          enable-cache: true
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4
        env:
          CIBW_BEFORE_BUILD: "python -m pip install --upgrade pip cython"
      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl
  build_sdist:
    runs-on: ubuntu-24.04
    environment: release
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          activate-environment: true
          enable-cache: true
      - name: Build
        run: uv build
      - uses: actions/upload-artifact@v7
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
  upload:
    runs-on: ubuntu-24.04
    environment: release
    needs: [build_wheels, build_sdist]
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
